name: trying to push to gcp

on:
    push:
        branches:
            - 'test-workflow'

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
        - name: install the gcloud cli
          uses: google-github-actions/setup-gcloud@v2
        #   with: 
        #     project_id: ${{ secrets.GOOGLE_PROJECT }}
        #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        #     export_default_credentials: true
        - name: auth of gcp cli
          uses: 'google-github-actions/auth@v2'
          with: 
            project_id: ${{ secrets.GOOGLE_PROJECT }}
            workload_identity_provider: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        - name: build and push docker image
          env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          run: |
            gcloud auth configure-docker europe-west3-docker.pkg.dev
            docker build -t europe-west3-docker.pkg.dev/$GOOGLE_PROJECT/checkers-actions .
            docker push europe-west3-docker.pkg.dev/$GOOGLE_PROJECT/checkers-actions