name: trying to push to gcp

on:
    push:
        branches:
            - 'test-workflow'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - id: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      
            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"
      
            - name: "Use gcloud CLI"
              run: "gcloud info"

            - name: "Docker auth"
              run: |-
                gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
            
            - name: Build Frontend
              run: docker build . --tag europe-west3-docker.pkg.dev/checkers-zsl/checkers-demo/frontend:1.0.4
              working-directory: checkers-frontend

            - name: Build Backend
              run: docker build . --tag europe-west3-docker.pkg.dev/checkers-zsl/checkers-demo/backend:1.0.4
              working-directory: checkers-backend
            
            - name: Publish Frontend
              run: docker push europe-west3-docker.pkg.dev/checkers-zsl/checkers-demo/frontend:1.0.4
            
            - name: Publish Backend
              run: docker push europe-west3-docker.pkg.dev/checkers-zsl/checkers-demo/backend:1.0.4