name: deploy to cloud run

on:
    workflow_dispatch:
        inputs:
            tag-version:
                required: true

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    REGION: ${{ secrets.REGION }}
    APP_NAME: ${{ secrets.DEV_APP_NAME }}
    REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
    SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
    TAG_VERSION: ${{ github.event.inputs.tag-version }}


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - id: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      
            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Deploy
              run: |-
                gcloud run deploy checkers --region europe-west3 --image europe-west3-docker.pkg.dev/checkers-zsl/checkers/frontend:1.0.4 --port 80