name: deploy to cloud run

on:
    workflow_dispatch:
        inputs:
            tag-version:
                required: true

env:
    PROJECT_ID: checkers-zsl
    REGION: europe-west3
    APP_FRONT_NAME: checkers-front
    ARTIFACT_REGISTRY_NAME: checkers
    FRONT_IMAGE: frontend
    TAG_VERSION: ${{ github.event.inputs.tag-version }}


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - id: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      
            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Deploy frontend
              run: |-
                gcloud run deploy $APP_FRONT_NAME --region $REGION --image $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_NAME/$FRONT_IMAGE:$TAG_VERSION --port 80
            - name: Deploy backend
              run: |-
                gcloud run deploy $APP_FRONT_NAME --region $REGION --image $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_NAME/$FRONT_IMAGE:$TAG_VERSION --port 8080