name: run tests

on:
    push:
        branches:
            - 'main'
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"
            
            - name: installing packages
              run: |-
                npm ci 
              working-directory: checkers-backend

            - name: running test
              run: |-
                npm run test
              working-directory: checkers-backend